name: Update README (Public Repos)

on:
  schedule:
    - cron: "0 0 * * *"   # runs daily at 00:00 UTC
  workflow_dispatch:       # allow manual runs from the Actions tab
  push:
    paths:
      - ".github/workflows/update-readme.yml"
      - "update_readme.py"
      - "README.md"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: pip install requests

      - name: Run updater
        env:
          GH_USERNAME: hritikmondal2003
          GH_TOKEN: ${{ secrets.GH_TOKEN }}   # optional but recommended
          MAX_REPOS: "15"
          INCLUDE_FORKS: "false"
        run: python update_readme.py

      - name: Commit & push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: auto-update public repo count/list in README"
          file_pattern: README.md
